language: csharp
mono:
  - latest

solution: PokeD.Server.Desktop.sln

before_install:
  - git submodule update --init --recursive
  
install:
  - nuget restore PokeD.Server.Desktop.sln

script:
  - mv /home/travis/build/PokeD/PokeD.Server.Desktop/packages/Open.Nat.2.1.0.0 /home/travis/build/PokeD/PokeD.Server.Desktop/packages/Open.NAT.2.1.0.0
  - xbuild /p:Configuration=Release PokeD.Server.Desktop.sln
  - xbuild /p:Configuration=Debug PokeD.Server.Desktop.sln

notifications:
  email:
    on_success: always
